### ISSUE TITLE
Add data model for coverage

### ISSUE THREAD

**Issue by ZoltanDominguez** [ZoltanDominguez/code_quality_inspector#1]

**Comment by KissPeter** [comment]
Are we looking for the overall numbers or tracking the changes at file level?
https://github.com/KissPeter/APIFuzzer/suites/13272269665/artifacts/723983492 is an example
This is the header:
`<coverage version="7.0.5" timestamp="1685540540660" lines-valid="1027" lines-covered="821" line-rate="0.7994" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0">
`
Line or Branch coverage, maybe both?

**Comment by ZoltanDominguez** [comment]
Current CoverageModel implementation aims to track both. Some tests will make it more obvious, but since the actual endpoint impl. is missing there is little to test now.

https://github.com/ZoltanDominguez/code_quality_inspector/blob/b26f0224731098bc6f2a75130b147325eb7f983d/code_quality_inspector/reporting/coverage/data_model/coverage_model.py#L19

**Comment by ZoltanDominguez** [comment]
Both meaning - both overall and per file
As well as - both line and branch.

An interesting question is how to calculate the diff, line and branch individually, or merge it somehow like coverage does in its final fail-below functionality.
